<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>8a4cccab-e318-4f48-bc21-87d017789f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdf-root']/div[4]/div[2]/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTUiIGhlaWdodD0iMTUiIHZpZXdCb3g9IjAgMCAxNSAxNSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEwLjgzNDQgMS41NDMxNEMxMS4wMDY2IDEuMzcwOTQgMTEuMjExIDEuMjM0MzUgMTEuNDM2IDEuMTQxMTZDMTEuNjYxIDEuMDQ3OTYgMTEuOTAyMSAxIDEyLjE0NTYgMUMxMi4zODkxIDEgMTIuNjMwMyAxLjA0Nzk2IDEyLjg1NTMgMS4xNDExNkMxMy4wODAyIDEuMjM0MzUgMTMuMjg0NyAxLjM3MDk0IDEzLjQ1NjkgMS41NDMxNEMxMy42MjkxIDEuNzE1MzMgMTMuNzY1NyAxLjkxOTc2IDEzLjg1ODggMi4xNDQ3NEMxMy45NTIgMi4zNjk3MyAxNCAyLjYxMDg2IDE0IDIuODU0MzlDMTQgMy4wOTc5MSAxMy45NTIgMy4zMzkwNCAxMy44NTg4IDMuNTY0MDNDMTMuNzY1NyAzLjc4OTAxIDEzLjYyOTEgMy45OTM0NCAxMy40NTY5IDQuMTY1NjNMNC42MDU5MyAxMy4wMTY2TDEgMTRMMS45ODM0NCAxMC4zOTQxTDEwLjgzNDQgMS41NDMxNFoiIGZpbGw9IndoaXRlIiBzdHJva2U9IiNFODNDMjYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPgo8L3N2Zz4K</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>button icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdf-root&quot;)/div[@class=&quot;css-14ywaby-PDFViewWrapper e9eg36l0&quot;]/div[@class=&quot;css-1wlarig-PDFPageWrapper e6kakxu0&quot;]/div[@class=&quot;css-mftv5m-PageWrapper e1ob5wfz0&quot;]/div[@class=&quot;css-129r1ij-FieldsListWrapper e1ob5wfz1&quot;]/div[@class=&quot;css-1s43bsu-FieldWrapper e1w4hxu80&quot;]/div[@class=&quot;css-1pczce6-FieldActions ez5m7ve0&quot;]/button[@class=&quot;css-stevrt-ButtonIcon e5710yz2&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdf-root']/div[4]/div[2]/div/div[2]/div[2]/div[2]/button/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='button icon'])[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/img</value>
   </webElementXpaths>
</WebElementEntity>
